---
- hosts: jump01.mikekletz.com
  gather_facts: true
  become: true
  tasks:
  - name: Install Apache
    dnf:
      name: 'httpd'
      state: latest

  - name: Verify Apache is running
    ansible.builtin.service:
      name: httpd
      state: started
