---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Create S3 bucket 
    amazon.aws.s3_bucket:
      name: "{{ s3_bucket_name }}"
      region: "{{ region }}"
      state: present

  - name: SQS queue allowing s3 bucket notifications
    sqs_queue:
      name: "eda_s3_notifications"
      region: "{{ region }}"
      default_visibility_timeout: 120
      message_retention_period: 86400
      maximum_message_size: 1024
      delivery_delay: 0
      receive_message_wait_time: 20
      policy:
        Version: 2012-10-17
        Id: s3-queue-policy
        Statement:
          - Sid: allowNotifications
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - SQS:SendMessage
            Resource: "arn:aws:sqs:*:*:eda_s3_notifications"
            Condition:
              ArnLike:
                aws:SourceArn: "arn:aws:s3:*:*:{{ s3_bucket_name }}"
    register: sqs_details

  - name: Setup bucket event notification to SQS
    community.aws.s3_bucket_notification:
      state: present
      region: "{{ region }}"
      event_name: on_file_add_or_remove
      bucket_name: "{{ s3_bucket_name }}"
      queue_arn: sqs_details.queue_arn
      events: ["s3:ObjectCreated:*"]
