---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Create SQS queue 
    community.aws.sqs_queue:
      name: eda-queue
      region: us-east-2
      default_visibility_timeout: 30
      message_retention_period: 86400
      maximum_message_size: 1024
      delivery_delay: 30
      receive_message_wait_time: 20
