---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Remove S3 bucket 
    amazon.aws.s3_bucket:
      name: "{{ s3_bucket_name }}"
      region: "{{ region }}"
      state: absent
      force: true

  - name: Remove SQS queue
    sqs_queue:
      name: "eda_s3_notifications"
      region: "{{ region }}"
      state: absent