---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Get new files from S3
    amazon.aws.s3_object:
      bucket: "{{ item.s3.bucket.name }}"
      region: "{{ item.awsRegion }}"
      object: "{{ item.s3.object.key }}"
      dest: "/tmp/{{ item.s3.object.key }}"
      mode: get
    with_items: "{{ ansible_eda.event.body.Records }}"


  - name: Find file
    ansible.builtin.find:
      paths: /tmp
      patterns: '*.yml'
