---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Get cat fact
    ansible.builtin.uri:
      url: https://catfact.ninja/fact
    register: cat_fact

  - name: Print cat_fact
    debug:
      msg: "{{ eda_event_body }}"
