---
- name: Listen for events on an AWS SQS Queue
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        region: us-east-2
        name: eda_s3_notifications
        delay_seconds: 10
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"

  rules:
    - name: Run template
      condition: event.body.Records is selectattr('eventName', '==', 'ObjectCreated:Put')
      action:
        #debug:
        #  msg: "{{ event.body }}"
        
        run_job_template:
          name: "AWS / EDA S3 download"
          organization: Default
          job_args:
              extra_vars:
                sqs_records: "{{ event.body.Records }}"
