---
- name: Listen for webhook from Splunk
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Run template
      action:
        run_job_template:
          name: "WINDOWS // Deploy IIS"
          organization: Default
