---
- name: Listen for webhook from Splunk
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Run template
      condition: event.meta.headers is defined
      action:
        run_job_template:
          name: "WINDOWS // Deploy IIS"
          organization: Default
          job_args:
            extra_vars:
              host: event.result.ComputerName
              survey_site_source: "https://www.free-css.com/assets/files/free-css-templates/download/page281/koppee.zip"
