---
- name: Listen for events on an AWS SQS Queue
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        region: us-east-2
        name: eda_s3_notifications
        delay_seconds: 10
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"
      filters:
        json_filter:
          include_keys: ['eventName']

  rules:
    - name: Run template
      condition: event.body != "poop"
      action:
        debug:
          msg: event.body
        
        #run_job_template:
        #  name: Cat Fact
        #  organization: Default
        #  job_args:
        #      extra_vars:
        #        eda_event_body: "{{ event.body }}"
