---
- name: Listen for events on a webhook
  hosts: localhost

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 192.168.1.194
        port: 5000

  ## Define the conditions we are looking for
  rules:
    - name: Run template
      condition: event.payload.message == "Ansible is super cool!"

  ## Define the action we should take should the condition be met

      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
