---
- name: Listen for events on an AWS SQS Queue
  hosts: localhost
  sources:
    - ansible.eda.aws_sqs_queue:
        region: us-east-2
        name: eda_s3_notifications
        delay_seconds: 10
        access_key: "{{ access_key }}"
        secret_key: "{{ secret_key }}"

  ## Define the conditions we are looking for
  rules:
    - name: Run template
      condition: "ObjectCreated:Put" in event.body
      action:
        run_job_template:
          name: Cat Fact
          organization: Default
